from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import httpx


def _request(client: httpx.Client, method: str, path: str, **kwargs: Any) -> httpx.Response:
    response = client.request(method, path, **kwargs)
    response.raise_for_status()
    return response


def run_smoke(base_url: str, sample_file: Path, cleanup: bool) -> dict[str, Any]:
    if not sample_file.exists():
        raise FileNotFoundError(f"Sample file not found: {sample_file}")

    title_suffix = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    course_id: int | None = None

    with httpx.Client(base_url=base_url, timeout=120.0) as client:
        health = _request(client, "GET", "/health").json()

        course = _request(
            client,
            "POST",
            "/courses",
            json={
                "title": f"OMSCS AI Smoke {title_suffix}",
                "description": "Generated by backend smoke demo.",
            },
        ).json()
        course_id = course["id"]

        with sample_file.open("rb") as file_handle:
            document = _request(
                client,
                "POST",
                "/documents/upload",
                data={"course_id": str(course_id)},
                files={"file": (sample_file.name, file_handle, "text/markdown")},
            ).json()

        summary = _request(
            client,
            "POST",
            f"/documents/{document['id']}/summaries",
            json={"summary_type": "concise"},
        ).json()

        flashcards = _request(
            client,
            "POST",
            f"/documents/{document['id']}/flashcards",
            json={"count": 5},
        ).json()

        quiz = _request(
            client,
            "POST",
            f"/documents/{document['id']}/quizzes",
            json={"question_count": 3, "difficulty": "mixed"},
        ).json()

        wrong_answers = [
            {"question_id": question["id"], "selected_answer": "Z"}
            for question in quiz["questions"]
        ]
        attempt = _request(
            client,
            "POST",
            f"/quizzes/{quiz['id']}/attempts",
            json={"answers": wrong_answers},
        ).json()

        weak_topics = _request(client, "GET", f"/courses/{course_id}/weak-topics").json()
        dashboard = _request(client, "GET", "/dashboard").json()

        if cleanup and course_id is not None:
            _request(client, "DELETE", f"/courses/{course_id}")

    if document["status"] != "extracted":
        raise RuntimeError(f"Expected extracted document, got {document['status']}")
    if not summary["key_points"]:
        raise RuntimeError("Expected generated summary key points")
    if len(flashcards) != 5:
        raise RuntimeError(f"Expected 5 flashcards, got {len(flashcards)}")
    if len(quiz["questions"]) != 3:
        raise RuntimeError(f"Expected 3 quiz questions, got {len(quiz['questions'])}")
    if attempt["total_questions"] != 3:
        raise RuntimeError("Expected attempt to score 3 questions")
    if not weak_topics:
        raise RuntimeError("Expected weak topics after intentionally wrong answers")

    return {
        "health": health,
        "course_id": course_id,
        "document_id": document["id"],
        "document_status": document["status"],
        "summary_id": summary["id"],
        "flashcard_count": len(flashcards),
        "quiz_id": quiz["id"],
        "question_count": len(quiz["questions"]),
        "attempt_score": attempt["score"],
        "weak_topic_count": len(weak_topics),
        "dashboard_counts": {
            "courses": dashboard["course_count"],
            "documents": dashboard["document_count"],
            "summaries": dashboard["summary_count"],
            "flashcards": dashboard["flashcard_count"],
            "quizzes": dashboard["quiz_count"],
        },
        "cleanup": cleanup,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the StudyPilot backend demo smoke flow.")
    repo_root = Path(__file__).resolve().parents[2]
    parser.add_argument("--base-url", default="http://127.0.0.1:8000")
    parser.add_argument(
        "--sample-file",
        type=Path,
        default=repo_root / "docs" / "demo" / "omscs_ai_sample_notes.md",
    )
    parser.add_argument("--cleanup", action="store_true", help="Delete the smoke course after validation.")
    args = parser.parse_args()

    result = run_smoke(args.base_url.rstrip("/"), args.sample_file, args.cleanup)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
